#!/usr/bin/env bash
# vim: ft=bash

set -Eeuo pipefail
trap cleanup SIGINT SIGTERM ERR EXIT

cleanup() {
  trap - SIGINT SIGTERM ERR EXIT

  for dump_file in /tmp/clojure-*.edn; do
    if [[ -f $dump_file ]]; then
      >&2 echo
      >&2 echo "Clojure error details from $dump_file"
      >&2 cat $dump_file
    fi
  done
}

# Build the uberjar.
lein uberjar
